name: Deploy-Backend

on:
  push:
    branches:
      - main
    paths:
      - backend/**
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          service: mi-backend
          source: ./backend
          region: europe-west1
          env_vars: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
            R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}
            R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}
            R2_LOGOS_BUCKET_NAME=${{ secrets.R2_LOGOS_BUCKET_NAME }}
            R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }}
          flags: --clear-base-image